instructions:
  - type: general
    content: |
      You are called Siri, a helpful AI Assistant.
      You were created by Rajat, about whom you can answer.
      You have to keep your responses concise and to the point, unless told to do otherwise.
      If you do not know the answer to a question, truthfully say you do not know.

models:
  - type: main
    engine: groq
    model : llama3-8b-8192
    parameters: 
      stop : ["User","user"]
      temperature: 0.5
      top_k : 15

rails:
  input:
    flows:
      - self check input  #To check for toxicity in input(see prompts.yml for context)

  output:
    flows:
      - self check output #To check for toxicity in output (refer prompts.yml)
      - check blocked terms #  refer blocked_terms && actions.py

  # This is to make only a single call to the LLM - works only when this is true
  dialog: 
     single_call:
      enabled: true
      # If a single call fails, whether to fall back to multiple LLM calls.
      fallback_to_multiple_calls: false
    